{% set name = "phidata" %}
{% set version = "2.4.38" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/phidata-{{ version }}.tar.gz
  sha256: c808b0f84a5499c418dc82d69999881e2d132ff8ff4445fc2a71f5bf4d30cd4b

build:
  entry_points:
    - phi = phi.cli.entrypoint:phi_cli
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - setuptools
    - pip
  run:
    - typing_extensions
    - python >=3.8
    - boto3
    - botocore
    - docker-py
    - gitpython
    - httpx
    - pydantic
    - pydantic-settings
    - python-dotenv
    - pyyaml
    - rich
    - tomli
    - typer
    - typing-extensions

test:
  imports:
    - phi
  commands:
    - pip check
    - phi --help
  requires:
    - pip

about:
  home: https://github.com/phidatahq/phidata
  summary: Build AI Assistants using function calling
  license: MPL-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
