schema_version: 1

context:
  name: phidata
  version: "2.7.10"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/phidata-${{ version }}.tar.gz
  sha256: d8d01e5e3841bf0df659f57d84a5eb5a8e5271fdf2f2899f6037f54839463482

build:
  number: 1
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  python:
    entry_points:
      - phi = phi.cli.entrypoint:phi_cli

requirements:
  host:
    - python ${{ python_min }}.*
    - setuptools
    - pip
  run:
    - docstring_parser
    - typing_extensions
    - python >=${{ python_min }}
    - boto3
    - botocore
    - docker-py
    - gitpython
    - httpx
    - pydantic
    - pydantic-settings
    - python-dotenv
    - pyyaml
    - rich
    - tomli
    - typer
    - typing-extensions

tests:
  - python:
      imports:
        - phi
      pip_check: true
      python_version: 
        - ${{ python_min }}
        - "*"
  - requirements:
      run:
        - pip
        - python ${{ python_min }}.*
    script:
      - phi --help

about:
  summary: Build AI Assistants using function calling
  license: MPL-2.0
  license_file: LICENSE
  homepage: https://github.com/phidatahq/phidata

extra:
  recipe-maintainers:
    - jan-janssen
